version: '3.8'
services:
  db:
    image: mysql:8.0
    platform: linux/amd64 # Явно указываем платформу
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: car_catalog
      TZ: Europe/Moscow # Часовой пояс для БД
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  app:
    build: ./app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: rootpass
      DB_NAME: car_catalog
      JWT_SECRET: verysecretkey_for_demo
      TZ: Europe/Moscow # Часовой пояс для приложения
    ports:
      - '3000:3000'
    # volumes:
    #   - ./app:/usr/src/app

volumes:
  db_data:
